
language: python


matrix:
    include:
        python: 2.7
        dist: xenial
        sudo: true

install:
    - pip install -r requirements.txt

# Run tests
script:
    - pytest
   


after_success:
    - coveralls